### ISSUE TITLE
Documentation Updation

### ISSUE THREAD

**Issue by rajsagare14** [rutuja310395/CricketBrowserGame#8]
Update README.md file

**Comment by rutuja310395** [comment]
ok @sarapapa-sp can you please do this?

**Comment by droffilc1** [comment]
Hello @rutuja310395 If it is still available I can work on it

**Comment by sarapapa-sp** [comment]
@rutuja310395  sure

**Comment by sarapapa-sp** [comment]
added the README.md documentation in #11
